#!/usr/bin/env bash
set -euo pipefail

SUBMIT_ROOT="$(pwd -P)"
SCRIPT_PATH="${BASH_SOURCE[0]}"
if [[ "${SCRIPT_PATH}" == */* ]]; then
  ROOT_DIR="$(cd "${SCRIPT_PATH%/*}" && pwd -P)"
else
  ROOT_DIR="${SUBMIT_ROOT}"
fi
cd "${ROOT_DIR}"

detect_cluster_env_name() {
  local -a args=("$@")
  local idx=0
  local cluster_name=""
  local slurm_profile_name=""
  while [[ ${idx} -lt ${#args[@]} ]]; do
    case "${args[${idx}]}" in
      --cluster)
        if [[ $((idx + 1)) -lt ${#args[@]} ]]; then
          cluster_name="${args[$((idx + 1))]}"
        fi
        idx=$((idx + 2))
        continue
        ;;
      --slurm-profile)
        if [[ $((idx + 1)) -lt ${#args[@]} ]]; then
          slurm_profile_name="${args[$((idx + 1))]}"
        fi
        idx=$((idx + 2))
        continue
        ;;
    esac
    idx=$((idx + 1))
  done
  if [[ -n "${cluster_name}" ]]; then
    printf '%s\n' "${cluster_name}"
    return 0
  fi
  case "${slurm_profile_name}" in
    euler_apptainer)
      printf '%s\n' "euler"
      ;;
    nrel_apptainer)
      printf '%s\n' "nrel"
      ;;
  esac
}

load_cluster_env_defaults() {
  local cluster_name="$1"
  if [[ -z "${cluster_name}" ]]; then
    return 0
  fi
  local env_file="${ROOT_DIR}/.env.slurm.${cluster_name}"
  if [[ ! -f "${env_file}" ]]; then
    return 0
  fi

  local -a preserve_vars=(
    MAXIONBENCH_SHARED_ROOT
    MAXIONBENCH_DATASET_ROOT
    MAXIONBENCH_DATASET_CACHE_DIR
    MAXIONBENCH_OUTPUT_ROOT
    MAXIONBENCH_FIGURES_ROOT
    MAXIONBENCH_HF_CACHE_DIR
    MAXIONBENCH_APPTAINER_CACHE_DIR
    MAXIONBENCH_APPTAINER_TMPDIR
    MAXIONBENCH_CONTAINER_IMAGE
    MAXIONBENCH_QDRANT_IMAGE
    MAXIONBENCH_PGVECTOR_IMAGE
    MAXIONBENCH_OPENSEARCH_IMAGE
    MAXIONBENCH_WEAVIATE_IMAGE
    MAXIONBENCH_MILVUS_ETCD_IMAGE
    MAXIONBENCH_MILVUS_MINIO_IMAGE
    MAXIONBENCH_MILVUS_IMAGE
    MAXIONBENCH_SLURM_ACCOUNT
    MAXIONBENCH_SLURM_PARTITION
    MAXIONBENCH_APPTAINER_MODULE
    MAXIONBENCH_MODULE_INIT_SH
    MAXIONBENCH_CLEANUP_LOCAL_SCRATCH
    MAXIONBENCH_CRAG_EXAMPLES
  )
  local -a preserve_set=()
  local -a preserve_values=()
  local idx=0
  local var_name=""
  for var_name in "${preserve_vars[@]}"; do
    if [[ "${!var_name+x}" == x ]]; then
      preserve_set[${idx}]=1
      preserve_values[${idx}]="${!var_name}"
    else
      preserve_set[${idx}]=0
      preserve_values[${idx}]=""
    fi
    idx=$((idx + 1))
  done

  # shellcheck disable=SC1090
  source "${env_file}"

  idx=0
  for var_name in "${preserve_vars[@]}"; do
    if [[ "${preserve_set[${idx}]}" == "1" ]]; then
      printf -v "${var_name}" '%s' "${preserve_values[${idx}]}"
      export "${var_name}"
    fi
    idx=$((idx + 1))
  done
  printf '%s\n' "+ loaded cluster env ${env_file}"
}

cluster_env_file_path() {
  local cluster_name="$1"
  if [[ -z "${cluster_name}" ]]; then
    return 1
  fi
  printf '%s\n' "${ROOT_DIR}/.env.slurm.${cluster_name}"
}

cluster_env_name() {
  if [[ -n "${CLUSTER}" ]]; then
    printf '%s\n' "${CLUSTER}"
    return 0
  fi
  if [[ -n "${AUTO_CLUSTER_ENV_NAME}" ]]; then
    printf '%s\n' "${AUTO_CLUSTER_ENV_NAME}"
    return 0
  fi
  case "${SLURM_PROFILE}" in
    euler_apptainer)
      printf '%s\n' "euler"
      ;;
    nrel_apptainer)
      printf '%s\n' "nrel"
      ;;
    *)
      return 1
      ;;
  esac
}

is_placeholder_value() {
  local value="$1"
  case "${value}" in
    your-account|YOUR_PRIVATE_ACCOUNT|your-partition|YOUR_PRIVATE_PARTITION)
      return 0
      ;;
    /shared/containers/*)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

validate_cluster_defaults() {
  local value=""
  for value in \
    "${MAXIONBENCH_SLURM_ACCOUNT:-}" \
    "${MAXIONBENCH_SLURM_PARTITION:-}" \
    "${MAXIONBENCH_CONTAINER_IMAGE:-}" \
    "${MAXIONBENCH_QDRANT_IMAGE:-}" \
    "${MAXIONBENCH_PGVECTOR_IMAGE:-}" \
    "${MAXIONBENCH_OPENSEARCH_IMAGE:-}" \
    "${MAXIONBENCH_WEAVIATE_IMAGE:-}" \
    "${MAXIONBENCH_MILVUS_ETCD_IMAGE:-}" \
    "${MAXIONBENCH_MILVUS_MINIO_IMAGE:-}" \
    "${MAXIONBENCH_MILVUS_IMAGE:-}"
  do
    if [[ -z "${value}" ]]; then
      continue
    fi
    if is_placeholder_value "${value}"; then
      echo "error: placeholder cluster-local value detected: ${value}" >&2
      echo "error: remove copied example values or override them with real cluster settings" >&2
      exit 2
    fi
  done
}

write_cluster_env_defaults() {
  local cluster_name=""
  cluster_name="$(cluster_env_name || true)"
  if [[ -z "${cluster_name}" ]]; then
    return 0
  fi
  local env_file=""
  env_file="$(cluster_env_file_path "${cluster_name}")"
  cat > "${env_file}" <<EOF
# Auto-generated by run_slurm_pipeline.sh for cluster ${cluster_name}
# This file is local and gitignored. Edit cluster-local knobs if needed.
MAXIONBENCH_SLURM_ACCOUNT=${MAXIONBENCH_SLURM_ACCOUNT:-}
MAXIONBENCH_SLURM_PARTITION=${MAXIONBENCH_SLURM_PARTITION:-}
MAXIONBENCH_SHARED_ROOT=${MAXIONBENCH_SHARED_ROOT}
MAXIONBENCH_DATASET_ROOT=${MAXIONBENCH_DATASET_ROOT}
MAXIONBENCH_DATASET_CACHE_DIR=${MAXIONBENCH_DATASET_CACHE_DIR}
MAXIONBENCH_OUTPUT_ROOT=${MAXIONBENCH_OUTPUT_ROOT}
MAXIONBENCH_FIGURES_ROOT=${MAXIONBENCH_FIGURES_ROOT}
MAXIONBENCH_HF_CACHE_DIR=${MAXIONBENCH_HF_CACHE_DIR}
MAXIONBENCH_APPTAINER_CACHE_DIR=${MAXIONBENCH_APPTAINER_CACHE_DIR}
MAXIONBENCH_APPTAINER_TMPDIR=${MAXIONBENCH_APPTAINER_TMPDIR}
MAXIONBENCH_APPTAINER_MODULE=${MAXIONBENCH_APPTAINER_MODULE:-apptainer}
MAXIONBENCH_MODULE_INIT_SH=${MAXIONBENCH_MODULE_INIT_SH:-}
MAXIONBENCH_CLEANUP_LOCAL_SCRATCH=${MAXIONBENCH_CLEANUP_LOCAL_SCRATCH:-1}
MAXIONBENCH_CONTAINER_IMAGE=${MAXIONBENCH_CONTAINER_IMAGE}
MAXIONBENCH_QDRANT_IMAGE=${MAXIONBENCH_QDRANT_IMAGE}
MAXIONBENCH_PGVECTOR_IMAGE=${MAXIONBENCH_PGVECTOR_IMAGE}
MAXIONBENCH_OPENSEARCH_IMAGE=${MAXIONBENCH_OPENSEARCH_IMAGE}
MAXIONBENCH_WEAVIATE_IMAGE=${MAXIONBENCH_WEAVIATE_IMAGE}
MAXIONBENCH_MILVUS_ETCD_IMAGE=${MAXIONBENCH_MILVUS_ETCD_IMAGE}
MAXIONBENCH_MILVUS_MINIO_IMAGE=${MAXIONBENCH_MILVUS_MINIO_IMAGE}
MAXIONBENCH_MILVUS_IMAGE=${MAXIONBENCH_MILVUS_IMAGE}
MAXIONBENCH_CRAG_EXAMPLES=${MAXIONBENCH_CRAG_EXAMPLES:-500}
EOF
  printf '%s\n' "+ wrote cluster env ${env_file}"
}

AUTO_CLUSTER_ENV_NAME="$(detect_cluster_env_name "$@")"
load_cluster_env_defaults "${AUTO_CLUSTER_ENV_NAME}"

CLUSTER=""
SLURM_PROFILE=""
CONTAINER_IMAGE="${MAXIONBENCH_CONTAINER_IMAGE:-}"
SHARED_ROOT="${MAXIONBENCH_SHARED_ROOT:-}"
DATASET_ROOT="${MAXIONBENCH_DATASET_ROOT:-}"
DATASET_CACHE_DIR="${MAXIONBENCH_DATASET_CACHE_DIR:-}"
OUTPUT_ROOT="${MAXIONBENCH_OUTPUT_ROOT:-}"
FIGURES_ROOT="${MAXIONBENCH_FIGURES_ROOT:-}"
HF_CACHE_DIR="${MAXIONBENCH_HF_CACHE_DIR:-}"
APPTAINER_CACHE_DIR="${MAXIONBENCH_APPTAINER_CACHE_DIR:-}"
APPTAINER_TMPDIR="${MAXIONBENCH_APPTAINER_TMPDIR:-}"
QDRANT_IMAGE="${MAXIONBENCH_QDRANT_IMAGE:-}"
PGVECTOR_IMAGE="${MAXIONBENCH_PGVECTOR_IMAGE:-}"
OPENSEARCH_IMAGE="${MAXIONBENCH_OPENSEARCH_IMAGE:-}"
WEAVIATE_IMAGE="${MAXIONBENCH_WEAVIATE_IMAGE:-}"
MILVUS_ETCD_IMAGE="${MAXIONBENCH_MILVUS_ETCD_IMAGE:-}"
MILVUS_MINIO_IMAGE="${MAXIONBENCH_MILVUS_MINIO_IMAGE:-}"
MILVUS_IMAGE="${MAXIONBENCH_MILVUS_IMAGE:-}"
SCENARIO_CONFIG_DIR="configs/scenarios_paper"
ENGINE_CONFIG_DIR="configs/engines"
RUN_MANIFEST_DIR="artifacts/slurm_manifests/latest"
SLURM_DIR="maxionbench/orchestration/slurm"
SEED="42"
SKIP_GPU=0
SKIP_S6=0
ALLOW_REDUCED_MATRIX=0
DRY_RUN=1

usage() {
  cat <<'EOF'
Usage:
  bash run_slurm_pipeline.sh --cluster <euler|nrel> [options]

Options:
  --cluster <name>               Cluster profile selector: euler or nrel
  --slurm-profile <name>         Explicit Slurm profile key override
                                 If present, .env.slurm.<cluster> is auto-loaded before CLI overrides
  --container-image <path>       Apptainer image path for Slurm jobs
  --shared-root <path>           Shared base directory; derives dataset/cache/results/figures/HF paths
  --dataset-root <path>          Shared dataset root (default: MAXIONBENCH_DATASET_ROOT)
  --dataset-cache-dir <path>     Shared dataset cache directory
  --output-root <path>           Shared run artifact root
  --figures-root <path>          Shared figure output root
  --hf-cache-dir <path>          Shared Hugging Face cache root
  --scenario-config-dir <path>   Scenario template directory for --full-matrix
  --engine-config-dir <path>     Engine config directory for --full-matrix
  --run-manifest-dir <path>      Output directory for generated run manifests
  --slurm-dir <path>             Slurm script directory
  --seed <int>                   Seed forwarded to submit-slurm-plan
  --skip-gpu                     Rejected for the hardened full-matrix rerun; GPU jobs are mandatory
  --skip-s6                      Defer S6 from the plan
  --allow-reduced-matrix         Allow a reduced smoke/debug matrix while still requiring GPU jobs
  --launch                       Prepare shared dirs/images and submit jobs; otherwise prints a dry-run plan
  --help                         Show this message
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --cluster)
      CLUSTER="$2"
      shift 2
      ;;
    --slurm-profile)
      SLURM_PROFILE="$2"
      shift 2
      ;;
    --container-image)
      CONTAINER_IMAGE="$2"
      shift 2
      ;;
    --shared-root)
      SHARED_ROOT="$2"
      shift 2
      ;;
    --dataset-root)
      DATASET_ROOT="$2"
      shift 2
      ;;
    --dataset-cache-dir)
      DATASET_CACHE_DIR="$2"
      shift 2
      ;;
    --output-root)
      OUTPUT_ROOT="$2"
      shift 2
      ;;
    --figures-root)
      FIGURES_ROOT="$2"
      shift 2
      ;;
    --hf-cache-dir)
      HF_CACHE_DIR="$2"
      shift 2
      ;;
    --scenario-config-dir)
      SCENARIO_CONFIG_DIR="$2"
      shift 2
      ;;
    --engine-config-dir)
      ENGINE_CONFIG_DIR="$2"
      shift 2
      ;;
    --run-manifest-dir)
      RUN_MANIFEST_DIR="$2"
      shift 2
      ;;
    --slurm-dir)
      SLURM_DIR="$2"
      shift 2
      ;;
    --seed)
      SEED="$2"
      shift 2
      ;;
    --skip-gpu)
      SKIP_GPU=1
      shift
      ;;
    --skip-s6)
      SKIP_S6=1
      shift
      ;;
    --allow-reduced-matrix)
      ALLOW_REDUCED_MATRIX=1
      shift
      ;;
    --launch)
      DRY_RUN=0
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "error: unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -z "${CLUSTER}" && -z "${SLURM_PROFILE}" ]]; then
  echo "error: provide --cluster or --slurm-profile" >&2
  exit 2
fi
if [[ "${SKIP_GPU}" -eq 1 ]]; then
  echo "error: full-matrix reruns require all GPU jobs; remove --skip-gpu" >&2
  exit 2
fi
case "$(printf '%s' "${MAXIONBENCH_ALLOW_GPU_UNAVAILABLE:-0}" | tr '[:upper:]' '[:lower:]')" in
  1|true|yes|on)
    echo "error: MAXIONBENCH_ALLOW_GPU_UNAVAILABLE=1 is not allowed for the hardened full-matrix rerun" >&2
    exit 2
    ;;
esac
if [[ -z "${SLURM_PROFILE}" ]]; then
  case "${CLUSTER}" in
    euler)
      SLURM_PROFILE="euler_apptainer"
      ;;
    nrel)
      SLURM_PROFILE="nrel_apptainer"
      ;;
    *)
      echo "error: --cluster must be euler or nrel" >&2
      exit 2
      ;;
  esac
fi
CLI_CMD=()
if command -v maxionbench >/dev/null 2>&1; then
  CLI_CMD=(maxionbench)
elif command -v python >/dev/null 2>&1; then
  CLI_CMD=(python -m maxionbench.cli)
elif command -v python3 >/dev/null 2>&1; then
  CLI_CMD=(python3 -m maxionbench.cli)
else
  echo "error: neither 'maxionbench' nor 'python'/'python3' is available in PATH" >&2
  exit 127
fi

default_shared_root() {
  if [[ -n "${SHARED_ROOT}" ]]; then
    printf '%s\n' "${SHARED_ROOT}"
    return 0
  fi
  printf '%s\n' "${ROOT_DIR}"
}

DEFAULT_SHARED_ROOT="$(default_shared_root)"

resolve_root_path() {
  local raw_path="$1"
  if [[ "${raw_path}" = /* ]]; then
    printf '%s\n' "${raw_path}"
    return 0
  fi
  printf '%s\n' "${ROOT_DIR}/${raw_path}"
}

default_container_path() {
  local current_path="$1"
  local image_name="$2"
  if [[ -n "${current_path}" ]]; then
    printf '%s\n' "${current_path}"
    return 0
  fi
  printf '%s\n' "${DEFAULT_SHARED_ROOT}/containers/${image_name}"
}

default_apptainer_cache_dir() {
  if [[ -n "${APPTAINER_CACHE_DIR}" ]]; then
    printf '%s\n' "${APPTAINER_CACHE_DIR}"
    return 0
  fi
  printf '%s\n' "${DEFAULT_SHARED_ROOT}/.cache/apptainer"
}

default_apptainer_tmpdir() {
  if [[ -n "${APPTAINER_TMPDIR}" ]]; then
    printf '%s\n' "${APPTAINER_TMPDIR}"
    return 0
  fi
  printf '%s\n' "${MAXIONBENCH_APPTAINER_CACHE_DIR}/tmp"
}

report_container_images() {
  printf '%s\n' "+ MAXIONBENCH_CONTAINER_IMAGE=${MAXIONBENCH_CONTAINER_IMAGE}"
  printf '%s\n' "+ MAXIONBENCH_QDRANT_IMAGE=${MAXIONBENCH_QDRANT_IMAGE}"
  printf '%s\n' "+ MAXIONBENCH_PGVECTOR_IMAGE=${MAXIONBENCH_PGVECTOR_IMAGE}"
  printf '%s\n' "+ MAXIONBENCH_OPENSEARCH_IMAGE=${MAXIONBENCH_OPENSEARCH_IMAGE}"
  printf '%s\n' "+ MAXIONBENCH_WEAVIATE_IMAGE=${MAXIONBENCH_WEAVIATE_IMAGE}"
  printf '%s\n' "+ MAXIONBENCH_MILVUS_ETCD_IMAGE=${MAXIONBENCH_MILVUS_ETCD_IMAGE}"
  printf '%s\n' "+ MAXIONBENCH_MILVUS_MINIO_IMAGE=${MAXIONBENCH_MILVUS_MINIO_IMAGE}"
  printf '%s\n' "+ MAXIONBENCH_MILVUS_IMAGE=${MAXIONBENCH_MILVUS_IMAGE}"
}

MISSING_IMAGE_PATHS=()

list_missing_image_paths() {
  local image_var=""
  local image_path=""
  for image_var in \
    MAXIONBENCH_CONTAINER_IMAGE \
    MAXIONBENCH_QDRANT_IMAGE \
    MAXIONBENCH_PGVECTOR_IMAGE \
    MAXIONBENCH_OPENSEARCH_IMAGE \
    MAXIONBENCH_WEAVIATE_IMAGE \
    MAXIONBENCH_MILVUS_ETCD_IMAGE \
    MAXIONBENCH_MILVUS_MINIO_IMAGE \
    MAXIONBENCH_MILVUS_IMAGE
  do
    image_path="${!image_var}"
    if [[ ! -f "${image_path}" ]]; then
      printf '%s=%s\n' "${image_var}" "${image_path}"
    fi
  done
}

read_missing_image_paths() {
  local image_record=""
  MISSING_IMAGE_PATHS=()
  while IFS= read -r image_record; do
    if [[ -z "${image_record}" ]]; then
      continue
    fi
    MISSING_IMAGE_PATHS[${#MISSING_IMAGE_PATHS[@]}]="${image_record}"
  done < <(list_missing_image_paths)
}

source_module_init() {
  if command -v module >/dev/null 2>&1; then
    return 0
  fi

  local candidate=""
  if [[ -n "${MAXIONBENCH_MODULE_INIT_SH:-}" ]]; then
    candidate="$(resolve_root_path "${MAXIONBENCH_MODULE_INIT_SH}")"
    if [[ -f "${candidate}" ]]; then
      # shellcheck disable=SC1090
      source "${candidate}"
      printf '%s\n' "+ sourced module init ${candidate}"
      if command -v module >/dev/null 2>&1; then
        return 0
      fi
    fi
  fi

  for candidate in \
    /etc/profile.d/modules.sh \
    /usr/share/Modules/init/bash \
    /etc/profile.d/lmod.sh \
    /usr/share/lmod/lmod/init/bash
  do
    if [[ ! -f "${candidate}" ]]; then
      continue
    fi
    # shellcheck disable=SC1090
    source "${candidate}"
    printf '%s\n' "+ sourced module init ${candidate}"
    if command -v module >/dev/null 2>&1; then
      return 0
    fi
  done

  return 1
}

ensure_apptainer() {
  if command -v apptainer >/dev/null 2>&1; then
    return 0
  fi

  local module_name="${MAXIONBENCH_APPTAINER_MODULE:-apptainer}"
  printf '%s\n' "+ apptainer not found in PATH; attempting module bootstrap with ${module_name}"
  if source_module_init && command -v module >/dev/null 2>&1; then
    printf '%s\n' "+ loading apptainer module ${module_name}"
    local module_output=""
    local module_status=0
    local module_log_file=""
    module_log_file="$(mktemp "${TMPDIR:-/tmp}/maxionbench_apptainer_module.XXXXXX")"
    set +e
    module load "${module_name}" >"${module_log_file}" 2>&1
    module_status=$?
    set -e
    if [[ -f "${module_log_file}" ]]; then
      module_output="$(cat "${module_log_file}")"
      rm -f "${module_log_file}"
    fi
    if [[ -n "${module_output}" ]]; then
      printf '%s\n' "+ module load ${module_name} output: ${module_output}"
    fi
    if [[ ${module_status} -eq 0 ]] && command -v apptainer >/dev/null 2>&1; then
      return 0
    fi
  fi

  echo "error: apptainer is required on the login/build node to prepare container images" >&2
  exit 2
}

prepare_shared_layout() {
  if [[ "${DRY_RUN}" -eq 1 ]]; then
    return 0
  fi
  mkdir -p \
    "${MAXIONBENCH_SHARED_ROOT}" \
    "${MAXIONBENCH_DATASET_ROOT}" \
    "${MAXIONBENCH_DATASET_CACHE_DIR}" \
    "${MAXIONBENCH_OUTPUT_ROOT}" \
    "${MAXIONBENCH_FIGURES_ROOT}" \
    "${MAXIONBENCH_HF_CACHE_DIR}" \
    "${MAXIONBENCH_APPTAINER_CACHE_DIR}" \
    "${MAXIONBENCH_APPTAINER_TMPDIR}" \
    "${MAXIONBENCH_SHARED_ROOT}/containers" \
    "${ROOT_DIR}/logs" \
    "$(resolve_root_path "${RUN_MANIFEST_DIR}")"
}

prepare_container_images() {
  if [[ "${DRY_RUN}" -eq 1 ]]; then
    return 0
  fi

  local build_script="${ROOT_DIR}/scripts/build_containers.sh"
  local definition_file="${ROOT_DIR}/maxionbench.def"
  if [[ ! -f "${build_script}" ]]; then
    echo "error: missing container build helper: ${build_script}" >&2
    exit 2
  fi
  if [[ ! -f "${definition_file}" ]]; then
    echo "error: missing Apptainer definition file: ${definition_file}" >&2
    exit 2
  fi

  ensure_apptainer
  printf '%s\n' "+ bash ${build_script} --output-dir ${MAXIONBENCH_SHARED_ROOT}/containers --only-missing"
  bash "${build_script}" --output-dir "${MAXIONBENCH_SHARED_ROOT}/containers" --only-missing
}

check_required_image_paths() {
  read_missing_image_paths
  if [[ "${#MISSING_IMAGE_PATHS[@]}" -eq 0 ]]; then
    return 0
  fi

  printf '%s\n' "warning: missing container images:" >&2
  printf '  %s\n' "${MISSING_IMAGE_PATHS[@]}" >&2
  if [[ "${DRY_RUN}" -eq 0 ]]; then
    echo "error: refusing to launch because required container images are missing" >&2
    exit 2
  fi
}

export MAXIONBENCH_SHARED_ROOT="${DEFAULT_SHARED_ROOT}"
export MAXIONBENCH_DATASET_ROOT="${DATASET_ROOT:-${DEFAULT_SHARED_ROOT}/dataset}"
export MAXIONBENCH_DATASET_CACHE_DIR="${DATASET_CACHE_DIR:-${DEFAULT_SHARED_ROOT}/.cache}"
export MAXIONBENCH_OUTPUT_ROOT="${OUTPUT_ROOT:-${DEFAULT_SHARED_ROOT}/results}"
export MAXIONBENCH_FIGURES_ROOT="${FIGURES_ROOT:-${DEFAULT_SHARED_ROOT}/figures}"
export MAXIONBENCH_HF_CACHE_DIR="${HF_CACHE_DIR:-${DEFAULT_SHARED_ROOT}/.cache/huggingface}"
export MAXIONBENCH_APPTAINER_CACHE_DIR="$(default_apptainer_cache_dir)"
export MAXIONBENCH_APPTAINER_TMPDIR="$(default_apptainer_tmpdir)"
export MAXIONBENCH_D3_DATASET_PATH="${MAXIONBENCH_DATASET_ROOT}/processed/D3/yfcc-10M/base.npy"
export MAXIONBENCH_CONTAINER_IMAGE="$(default_container_path "${CONTAINER_IMAGE}" "maxionbench.sif")"
export MAXIONBENCH_QDRANT_IMAGE="$(default_container_path "${QDRANT_IMAGE}" "qdrant.sif")"
export MAXIONBENCH_PGVECTOR_IMAGE="$(default_container_path "${PGVECTOR_IMAGE}" "pgvector.sif")"
export MAXIONBENCH_OPENSEARCH_IMAGE="$(default_container_path "${OPENSEARCH_IMAGE}" "opensearch.sif")"
export MAXIONBENCH_WEAVIATE_IMAGE="$(default_container_path "${WEAVIATE_IMAGE}" "weaviate.sif")"
export MAXIONBENCH_MILVUS_ETCD_IMAGE="$(default_container_path "${MILVUS_ETCD_IMAGE}" "milvus-etcd.sif")"
export MAXIONBENCH_MILVUS_MINIO_IMAGE="$(default_container_path "${MILVUS_MINIO_IMAGE}" "milvus-minio.sif")"
export MAXIONBENCH_MILVUS_IMAGE="$(default_container_path "${MILVUS_IMAGE}" "milvus.sif")"
CONTAINER_IMAGE="${MAXIONBENCH_CONTAINER_IMAGE}"

validate_cluster_defaults
write_cluster_env_defaults
prepare_shared_layout
prepare_container_images
report_container_images
check_required_image_paths
CMD=(
  "${CLI_CMD[@]}"
  submit-slurm-plan
  --slurm-dir "${SLURM_DIR}"
  --slurm-profile "${SLURM_PROFILE}"
  --scenario-config-dir "${SCENARIO_CONFIG_DIR}"
  --engine-config-dir "${ENGINE_CONFIG_DIR}"
  --run-manifest-dir "${RUN_MANIFEST_DIR}"
  --seed "${SEED}"
  --container-runtime apptainer
  --container-image "${CONTAINER_IMAGE}"
  --output-root "${MAXIONBENCH_OUTPUT_ROOT}"
  --download-datasets
  --preprocess-datasets
  --prefetch-datasets
  --include-postprocess
  --full-matrix
  --json
)

if [[ -n "${MAXIONBENCH_HF_CACHE_DIR}" ]]; then
  CMD+=(--hf-cache-dir "${MAXIONBENCH_HF_CACHE_DIR}")
fi
if [[ "${SKIP_S6}" -eq 1 ]]; then
  CMD+=(--skip-s6)
fi
if [[ "${ALLOW_REDUCED_MATRIX}" -eq 1 ]]; then
  CMD+=(--allow-reduced-matrix)
fi
if [[ "${DRY_RUN}" -eq 1 ]]; then
  CMD+=(--dry-run)
fi

echo "+ ${CMD[*]}"
"${CMD[@]}"
