package ctxmgr

import (
	"encoding/json"
	"fmt"
	"os"
	"reflect"
	"strings"
	"testing"
	"time"
)

type parityFixture struct {
	MaskText  string `json:"mask_text"`
	Histories []struct {
		History []Message `json:"history"`
		Steps   []int     `json:"steps"`
	} `json:"histories"`
	Cases []struct {
		History      int     `json:"history"`
		Policy       string  `json:"policy"`
		Keep         int     `json:"keep"`
		BudgetTokens int     `json:"budget_tokens"`
		MinGrowth    int     `json:"min_growth"`
		Views        [][]any `json:"views"`
	} `json:"cases"`
}

// decode turns a fixture view (history indexes, ["mask", i] for masked tool results) into messages.
func decode(t *testing.T, enc []any, history []Message) []Message {
	t.Helper()
	out := make([]Message, len(enc))
	for i, e := range enc {
		switch x := e.(type) {
		case float64:
			out[i] = history[int(x)]
		case []any:
			out[i] = replaceContent(history[int(x[1].(float64))], MaskText)
		default:
			t.Fatalf("bad fixture entry %v", e)
		}
	}
	return out
}

// TestParityWithPython replays the histories generated by tests/test_gateway_context_parity.py and expects
// the exact views Python's CacheAware produced, step by step.
func TestParityWithPython(t *testing.T) {
	raw, err := os.ReadFile("testdata/parity.json")
	if err != nil {
		t.Fatal(err)
	}
	var fx parityFixture
	if err := json.Unmarshal(raw, &fx); err != nil {
		t.Fatal(err)
	}
	if fx.MaskText != MaskText {
		t.Fatalf("mask text differs from Python: %q", fx.MaskText)
	}
	for ci, c := range fx.Cases {
		h := fx.Histories[c.History]
		m := New(Config{Policy: c.Policy, Keep: c.Keep, BudgetTokens: c.BudgetTokens, MinGrowth: c.MinGrowth, MaxSessions: 10})
		now := time.Unix(0, 0)
		for si, n := range h.Steps {
			got := m.Apply("s", h.History[:n], now)
			want := decode(t, c.Views[si], h.History)
			if !reflect.DeepEqual(got.View, want) {
				t.Fatalf("case %d (%s keep %d budget %d) step %d: view differs from Python", ci, c.Policy, c.Keep,
					c.BudgetTokens, si)
			}
			now = now.Add(time.Second)
		}
	}
}

func agentHistory(exchanges, resultChars int) []Message {
	h := []Message{{"role": "system", "content": "sys"}, {"role": "user", "content": "task"}}
	for e := range exchanges {
		id := fmt.Sprintf("c%d", e)
		h = append(h,
			Message{"role": "assistant", "content": nil, "tool_calls": []any{map[string]any{"id": id, "type": "function",
				"function": map[string]any{"name": "search", "arguments": `{"q":"x"}`}}}},
			Message{"role": "tool", "tool_call_id": id, "content": strings.Repeat("y", resultChars)})
	}
	return h
}

func TestAppendOnlyUntilBudgetThenEdit(t *testing.T) {
	m := New(Config{Policy: "mask+cache", Keep: 2, BudgetTokens: 1000, MaxSessions: 10})
	now := time.Unix(0, 0)
	var actions []string
	var prev []Message
	for e := 0; e <= 12; e++ {
		r := m.Apply("s", agentHistory(e, 400), now) // ~110 tokens per exchange
		actions = append(actions, r.Action)
		if r.Action == Append && !reflect.DeepEqual(r.View[:len(prev)], prev) {
			t.Fatalf("exchange %d: append changed the earlier view", e)
		}
		if r.TokensOut > 1000 {
			t.Fatalf("exchange %d: view %d tokens over budget", e, r.TokensOut)
		}
		prev = r.View
		now = now.Add(time.Second)
	}
	if actions[0] != Start || !contains(actions, Append) || !contains(actions, Edit) {
		t.Fatalf("actions %v: want start, appends and at least one edit", actions)
	}
}

// When the masked view of a long history is itself over budget, every call would re-render it (and miss the
// cache); min_growth makes the next re-render wait until the view has grown.
func TestMinGrowthStopsRetrimEveryCall(t *testing.T) {
	edits := func(growth int) int {
		m := New(Config{Policy: "mask+cache", Keep: 1, BudgetTokens: 300, MinGrowth: growth, MaxSessions: 10})
		n := 0
		for e := 0; e <= 40; e++ { // each masked result still costs ~23 tokens, so the masked view passes 300
			if r := m.Apply("s", agentHistory(e, 400), time.Unix(int64(e), 0)); r.Action == Edit {
				n++
			}
		}
		return n
	}
	if without, with := edits(0), edits(500); without < 30 || with > 10 {
		t.Fatalf("edits without min_growth %d (want thrash), with %d (want few)", without, with)
	}
}

func TestDivergedHistoryRestarts(t *testing.T) {
	m := New(Config{Policy: "window+cache", Keep: 2, BudgetTokens: 100_000, MaxSessions: 10})
	now := time.Unix(0, 0)
	m.Apply("s", agentHistory(3, 100), now)
	if r := m.Apply("s", agentHistory(4, 100), now); r.Action != Append {
		t.Fatalf("extension: got %s", r.Action)
	}
	compacted := agentHistory(1, 100) // the client rewrote its own history
	compacted[1] = Message{"role": "user", "content": "summary of earlier work"}
	if r := m.Apply("s", compacted, now); r.Action != Start {
		t.Fatalf("divergence: got %s", r.Action)
	}
}

func TestPauseTriggerTrimsEarly(t *testing.T) {
	cfg := Config{Policy: "mask+cache", Keep: 1, BudgetTokens: 100_000, PauseS: 300, MaxSessions: 10}
	m := New(cfg)
	t0 := time.Unix(0, 0)
	m.Apply("s", agentHistory(4, 400), t0)
	if r := m.Apply("s", agentHistory(5, 400), t0.Add(299*time.Second)); r.Action != Append {
		t.Fatalf("short pause: got %s", r.Action)
	}
	r := m.Apply("s", agentHistory(6, 400), t0.Add(700*time.Second))
	if r.Action != PauseEdit || r.TokensOut >= r.TokensIn {
		t.Fatalf("long pause: got %s, %d -> %d tokens", r.Action, r.TokensIn, r.TokensOut)
	}
}

func TestEvictsLeastRecentlyUsed(t *testing.T) {
	m := New(Config{Policy: "mask+cache", Keep: 2, BudgetTokens: 1000, MaxSessions: 2})
	t0 := time.Unix(0, 0)
	m.Apply("a", agentHistory(1, 10), t0)
	m.Apply("b", agentHistory(1, 10), t0.Add(time.Second))
	m.Apply("a", agentHistory(2, 10), t0.Add(2*time.Second))
	m.Apply("c", agentHistory(1, 10), t0.Add(3*time.Second)) // evicts b
	if m.Sessions() != 2 {
		t.Fatalf("sessions %d", m.Sessions())
	}
	if r := m.Apply("a", agentHistory(3, 10), t0.Add(4*time.Second)); r.Action != Append {
		t.Fatalf("a should survive: %s", r.Action)
	}
	if r := m.Apply("b", agentHistory(2, 10), t0.Add(5*time.Second)); r.Action != Start {
		t.Fatalf("b should have been evicted: %s", r.Action)
	}
}

func TestValidate(t *testing.T) {
	for _, p := range []string{"", "off", "mask+cache", "window+cache"} {
		c := Config{Policy: p}
		if err := c.Validate(); err != nil {
			t.Fatalf("%q: %v", p, err)
		}
	}
	c := Config{Policy: "summarize"}
	if c.Validate() == nil {
		t.Fatal("summarize should be rejected")
	}
	c = Config{Policy: "mask+cache"}
	c.Validate() //nolint:errcheck
	if c.Keep != 4 || c.BudgetTokens != 64_000 {
		t.Fatalf("defaults: %+v", c)
	}
}

func contains(xs []string, x string) bool {
	for _, y := range xs {
		if y == x {
			return true
		}
	}
	return false
}
